title: WISDM
theme: minima
description: Powered by Jekyll and Minima
author: Apex Resource Management Solutions
email: info@apexrms.com
header_pages:
  - index.md
collections:
  sections:
    output: true